### ISSUE TITLE
有关[error]session is null问题

### ISSUE THREAD

**Issue by fanfq** [YeautyYE/netty-websocket-spring-boot-starter#62]
YYE你好，我原本的微服务是用springboot tomcat websocket做的，现在想优化一下转netty刚好看到的你的开源项目，可以做到无缝移植。当我配置好之后业务逻辑也都是正常的，但是服务器端一直提示。

`org.yeauty.pojo.PojoEndpointServer.doOnClose(113) | session is null`

直到无socket连接才不会显示此条日志。不太清楚是什么原因特来请教。谢谢，

以下是我的配置，其他的都是follow你的demo
```
netty-websocket: 
  host: localhost
  path: /gs
  port: 9091
```
